### ISSUE TITLE
scons: *** [.pioenvs/uno/src/tmp_ino_to.o] No such file or directory

### ISSUE THREAD

**Issue by jeancdc** [vigetlabs/platomformio#14]
I've got this error in the log when I compile a program:

```
scons: *** [.pioenvs/uno/src/tmp_ino_to.o] No such file or directory
```

Atom 1.2.0, PlatomformIO 0.6.1, PlatformIO 2.3.4, Mac OSX 10.11.1

**Comment by jeancdc** [comment]
This problem appears when I use CMD+SHIFT+B in the Atom editor but it works when I use this command in the terminal:
`platformio run`.

Some help ?

**Comment by efatsi** [comment]
Having a hard time reproducing this, any ideas @ivankravets?

**Comment by ivankravets** [comment]
@efatsi Firstly, thanks a lot for this plugin!!!  I don't know why, but for the last month Atom IDE + this plugin is #1 in the our IDE supported list by popularity. This is great!

Secondly, as for the this issue - I've just installed Atom 1.2.0, then this plugin and built a few projects without any problems and additional steps. Works from a box :+1: 

@jeancdc sorry for the "stupid" help, could you provide me access to the PC where I can reproduce this issue? TeamViewer is preferable. You can contact me@ikravets.com directly with ID/Pass for the session. Thanks in advance!

**Comment by arif-dewi** [comment]
Same problem. Just installed last Atom on the last MacOs X with last version of plugin - gives the same result =>

> scons: **\* [.pioenvs/uno/src/tmp_ino_to.o] No such file or directory 

There is nothing inside src directory.
Same here:  https://travis-ci.org/nichtich/platformio-arduino
Interesting but 

> platformio run

runs without any errors

**Comment by ivankravets** [comment]
Dear @andrewdonskikh, @jeancdc,

Could someone provide me access to Mac where I can reproduce this issue?(or even video). I can't reproduce this issue on my Mac.

TeamViewer is preferable. You can contact me@ikravets.com directly with ID/Pass for the session. 

Thanks in advance!

**Comment by openroc** [comment]
I had the same problem,  Atom 1.2.4 + platformio 2.4.1 + platomformio 0.6.1

http://i.imgur.com/qBZ699z.png

**Comment by ivankravets** [comment]
Dear @openroc, could I debug this issue using your PC under your control via TeamViewer? Thanks in advance!

**Comment by ivankravets** [comment]
@openroc do you run build process within opened file from  `src` directory?

**Comment by openroc** [comment]
@ivankravets I built the project in Terminal with platformio command successfully, I use atom to open the project folder, not the src folder. 

the screenshots as follows,

http://i.imgur.com/LulKkMe.png
http://i.imgur.com/IBUGPPF.jpg

**Comment by ivankravets** [comment]
Try to remove `.pioenvs` directory and build using Atom(not Terminal). Did it help?

**Comment by openroc** [comment]
still failed with new error, 

http://i.imgur.com/Sy0ZKt9.png

I checked, it's empty in .pioenvs/uno/src.

**Comment by ivankravets** [comment]
The last test: please remove `.pioenvs` dir and `.sconsign.db`

**Comment by openroc** [comment]
the same error as previous one

**Comment by openroc** [comment]
@ivankravets Just took a look at your code, and I found that this bug is because of the changing env.PATH, and when I use the process.env instead as follows,

54   run: (command, args) ->
 55     startTime = new Date()
 56
 57     # Default to where the user opened atom
 58     options =
 59       cwd: @getCwd()
 60       env: process.env
 61     #options.env.PATH = atom.config.get('platomformio.environPath')
 62     options.env.PATH = process.env.PATH
 63     console.log('====', options)
 64

maybe the best way is ( should check if the environPath is empty)

options.env.PATH = atom.config.get('platomformio.environPath') + ":" +process.env.PATH

**Comment by ivankravets** [comment]
@openroc I've just mailed you. I'm waiting for the answer. :clock1:

**Comment by ivankravets** [comment]
> Just took a look at your code

This isn't my code. I'm here as support for @PlatformIO. I'm not well familiar with Atom coding.

> options.env.PATH = atom.config.get('platomformio.environPath') + ":" +process.env.PATH

Does it fix this issue? We will ask @efatsi to review it.

**Comment by efatsi** [comment]
I've added the `process.env.PATH` to the path options and released a version `0.6.2`. Let me know if that fixes it for you guys.

**Comment by openroc** [comment]
@efatsi just upgrade to 0.6.2, it works now!. :)

@ivankravets it's not a BUG of platformio, just because of a wrong env PATH for running it when spawn it.

**Comment by jeancdc** [comment]
OK. It works now.
Thanks.

**Comment by ivankravets** [comment]
Guys,

> options.env.PATH = atom.config.get('platomformio.environPath') + ":" +process.env.PATH

This isn't valid solution because when user's setting is empty we receive broken PATH, like `:/a/b..:/a/b/c`. Also, when user inputed own PATH then we SHOULD NOT add something "new".

I've just fixed it in https://github.com/vigetlabs/platomformio/commit/4f969bf3f16b8dc4d704422702dacb1c33c4a992

Also, updated all related files (CHAGES, README, etc).

@efatsi  please release 0.6.3.

Thanks a lot for your reports!

**Comment by openroc** [comment]
:+1:

**Comment by efatsi** [comment]
Part of me is still confused on what the root issue is here. If adding something to the `path` passed in to the command was the solution, then were you not able to just set a correct path in the package settings and clear the issue?

I've released `0.6.3`, @openroc if you want to confirm it still works, that would be great. Even greater would be if you had any ideas on how I would be able to reproduce this issue. Thanks.

**Comment by ivankravets** [comment]
@efatsi the problem is linked with empty `process.env.PATH`. You can't reproduce it because you have filled "package's PATH" setting. For the new users "package's PATH" is empty. What is more, we have overridden SYSTEM PATH with "empty PATH" using `options.env.PATH = atom.config.get('platomformio.environPath')`.

Finally, this issue is related to the new users with empty package settings. By default, package will use SYSTEM PATH now if `atom.config.get('platomformio.environPath')` is empty.

**Comment by efatsi** [comment]
Ah, so it was an issue only if users hadn't properly set their PATH setting. It looks like I am able to reproduce this if I fiddle with my packages' path settings enough.

I'm going to add a line in the README setup instructing users to set the PATH setting on install. I'd assumed if it wasn't set properly than the `platformio` command wouldn't be available and we'd display the error instructing to update PATH. Looks like `platformio` can be available but not completely.

**Comment by ivankravets** [comment]
I've just opened related issue #15. I propose to move our discussion here. As I said, in 60-70% no need to specify PATH. the base system env.PATH is good when user is installed PlatformIO to global system.

This issue is related to users which install @PlatformIO into special virtual environments (https://virtualenv.readthedocs.org/en/latest/) or in the place where `/bin` isn't added to system PATH.

To avoid this problem we can inform user before CMD/RUN that he should go to settings and customise own env.PATH.

**Comment by openroc** [comment]
@efatsi @ivankravets just upgrade to 0.6.3, the bug was reproduced

**Comment by ivankravets** [comment]
@openroc which your `echo $PATH`?

**Comment by openroc** [comment]
@ivankravets bash: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:

**Comment by openroc** [comment]
Currently, I used terminal(zsh or bash) in mac environment, and I had set the /usr/local/bin to my bashrc and zshrc.

**Comment by efatsi** [comment]
@openroc are you saying that the bug has returned in 0.6.3? If you type `echo $PATH` in your terminal, and paste the outcome into the `Environment PATH` package settings the issue should go away.

**Comment by ivankravets** [comment]
@openroc and these?

```
$ which platformio
$ which scons
```

**Comment by openroc** [comment]
roc ~$ which platformio
/usr/local/bin/platformio
roc ~$ which scons
/usr/local/bin/scons

@efatsi  yes, :(,

**Comment by openroc** [comment]
@ivankravets I can build project successfully by platformio in command line.

**Comment by openroc** [comment]
just took a look at the changed code, I found the problem is because that I set the path in platomformio ,
but in the code in 0.6.3, the env was overwritten by the atom.config setting, and lost the process.env.

```
# override PATH with the user value
if atom.config.get('platomformio.environPath')
  options.env.PATH = atom.config.get('platomformio.environPath')
```

supposed to change to

```
# override PATH with the user value
if atom.config.get('platomformio.environPath')
  options.env.PATH = atom.config.get('platomformio.environPath') + process.env.PATH
```

**Comment by ivankravets** [comment]
@openroc you didn't answer to @efatsi question above

> If you type echo $PATH in your terminal, and paste the outcome into the Environment PATH package settings the issue should go away.

**Comment by openroc** [comment]
just tested, it works for me.

**Comment by openroc** [comment]
this bug is because that the env Path was overwritten by user, when user set the platformio path in the platomformio setting page. for example, I set '/usr/local/bin' in the platomformio setting page. the other path will be lost for node  spawning child process, I think it's clear now.

  # override PATH with the user value
  if atom.config.get('platomformio.environPath')
    options.env.PATH = atom.config.get('platomformio.environPath')

**Comment by ivankravets** [comment]
@efatsi, do you understand @openroc? Because I don't understand. :frowning:

@openroc PLEASE uninstall modified package(I see that you have made own changes to code) and
1. Install CLEAN 0.6.3 version
2. Go to settings pane and fill env.PATH with result of `echo $PATH`. In your case, it is `/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin`

Does it work for you WITHOUT ANY MODIFICATIONS to source code?

**Comment by openroc** [comment]
@ivankravets  the problem is , in previous 0.6.2, the path of platomformio setting page was set to '/user/local/bin' (this is not the full path as you said, "echo $PATH"). and after upgrading to v0.6.3, the path setting was remained, and so the bug was reproduced.

so, in the new version 0.6.3, I set empty or the full path there, it will build successfully.
