### ISSUE TITLE
Use linter for messaging

### ISSUE THREAD

**Issue by steelbrain** [vigetlabs/platomformio#3]
Just like the title says

**Comment by Rickgg** [comment]
What messaging are you referring to, exactly?

**Comment by steelbrain** [comment]
You are currently using `atom-message-panel`, We have a lot of cool features like tabs and diff based DOM updates and traces and such. Besides linter was made to be used this way.

**Comment by Rickgg** [comment]
Yes, I think so too... I forked the repo and will work on an option for `atom-notifications` instead of `atom-message-panel`. Any other ideas or settings you would like?

**Comment by steelbrain** [comment]
Using notifications for linter messages is just abuse IMO. There are tons of linter providers out there, there won't be any space left on the screen of the user if all of them used a message panel of themselves instead of consuming the linter API. besides, the linter API is easier than the panel and their updates and all that, isn't it?

**Comment by Rickgg** [comment]
Ohh sorry, I didn't understand before (probably because I hadn't searched for Linter), but now that I understand, I think you're right, it would be a great addition!
I was thinking of adding the message panels for when uploading or building was complete, as a small feature. I'm still learning, so I try to take little steps. :smile:

**Comment by efatsi** [comment]
Looks like discussion has died down here, going to close the issue.
